config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'profile', to: 'profile#edit', as: :edit_profile
  put 'profile', to: 'profile#update'
  get 'profile/rc', to: 'profile#rc'

  resources :scripts do
    member do
      get 'editor'
    end
  end

  root 'index#index'
end

app/models/script.rb
require('open-uri')
class Script < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :user

  validates :language,  presence: true, inclusion: { in: %w( javascript coffeescript ) }
  validates :user,      presence: true
  validates :title,     presence: true

  def language=(value)
    write_attribute :language, value.downcase
  end

  def language_value
    case language
    when 'javascript'
      'JavaScript'
    when 'coffeescript'
      'CoffeeScript'
    else
      language
    end
  end

  def extension
    case language
    when 'javascript'
      ".js"
    when 'coffeescript'
      ".coffee"
    else
      ".coffee"
    end
  end

  def has_content?
    aws_id.present?
  end

  def content_url
    "https://s3-#{ENV['AWS_REGION']}.amazonaws.com/#{ENV['AWS_S3_BUCKET_NAME']}/#{aws_path}" if has_content?
  end

  def compiled_content_url
    "https://s3-#{ENV['AWS_REGION']}.amazonaws.com/#{ENV['AWS_S3_BUCKET_NAME']}/#{compiled_aws_path}" if has_content?
  end

  def compiled_content
    open(content_url).read if has_content?
  end

  def compiled_content=(content)
    self.aws_id ||= SecureRandom.hex
    Aws::S3::Client.new.put_object( body: content, key: compiled_aws_path, acl: 'public-read', bucket: ENV['AWS_S3_BUCKET_NAME'] )
    content
  end

  def content
    open(content_url).read if has_content?
  end

  def content=(content)
    self.aws_id ||= SecureRandom.hex
    Aws::S3::Client.new.put_object( body: content, key: aws_path, acl: 'public-read', bucket: ENV['AWS_S3_BUCKET_NAME'] )
    content
  end

  private
    def aws_path
      "scripts/#{aws_id}"
    end

    def compiled_aws_path
      "compiled-scripts/#{aws_id}"
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :scripts, -> { order('updated_at DESC') }

  validates :keyboard,  inclusion: { in: %w( default vim emacs ) }
  validates :rc,        length: { maximum: 5_000 }

  def keyboard=(value)
    write_attribute :keyboard, value.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout_by_resource

  protected

    def layout_by_resource
      devise_controller? ? "devise" : "application"
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :rc
  before_action :authenticate_user!
  before_action :set_user

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:info] = "Changes saved."
      redirect_to :edit_profile
    else
      render action: :edit
    end
  end

  def rc
    render js: (@user.rc || "")
  end

  private
  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:keyboard, :rc)
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_script, only: [:edit, :editor, :update, :destroy]

  protect_from_forgery with: :exception

  def index
    @scripts = current_user.scripts.order("updated_at DESC")
    @script_count = current_user.scripts.count
  end

  def show
    @script = Script.find(params[:id])
  end

  def new
    @script = Script.new
  end

  def edit
  end

  def editor
  end

  def create
    @script = Script.new(script_params)
    @script.user = current_user

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render :show, status: :created, location: @script }
      else
        format.html { render :new }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @script.touch
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to script_path(@script), notice: 'Updated script' }
        format.json { render json: {}, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @script.destroy
      redirect_to({action: :index}, {notice: "Deleted #{@script.title}"})
    else
      redirect_to({action: :index}, {alert: "Unable to delete #{@script.title}"})
    end
  end

  private
    def set_script
      @script = current_user.scripts.find(params[:id])
    end

    def script_params
      params.require(:script).permit(:title, :description, :compiled_content, :content, :language)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_editor?
    controller.controller_name == 'scripts' && controller.action_name == 'editor'
  end

  def script_content_url(script)
    if script.has_content?
      script.content_url
    else
      'https://s3-us-west-1.amazonaws.com/synthdrop/scripts/dc8606ea6d98885e517e898cb60ca304'
    end
  end
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/index/index.html.erb
<div class="container">
  <div class="alert alert-success">
    <span class="glyphicon glyphicon-bullhorn"></span>
    <span>
      Hi! Feel free to sign up and dig in but know the site isn't totally ready for launch. (Use Safari for now.)
    </span>
  </div>

  <div class="jumbotron">

    <h2>Make some music</h2>

    <p>
      Edit the code below and explore how easy it is to write your own audio generator.
    </p>

    <div id="editor" class="demo blur" style="height: 100px;" data-content-url="https://s3-us-west-1.amazonaws.com/synthdrop/scripts/dc8606ea6d98885e517e898cb60ca304" data-language="coffeescript" data-keyboard="<%= current_user.try(:keyboard) %>">Loading</div>

    <%= link_to "Play", '#', id: 'play-btn', class: 'btn btn-primary', title: 'cmd + enter' %>
    <%= link_to "Stop", '#', id: 'stop-btn', class: 'btn btn-primary', title: 'cmd + .' %>

    <div class="pull-right" style="padding-top: 20px;">
      <span class="label label-default">Coffeescript</span>
    </div>

    <% if false %>

      <h2>The easiest, fastest way to create music.</h2>

      <h2> Music Hackers </h2>
      <h2> A Place for JavaScript Musicians </h2>

      <ul>
        <li> Sophisticated javascript tools for creating and sharing electronic music </li>
        <li> Share your music with others </li>
        <li> Show off </li>
        <li> Easily share with folks </li>
        <li> Community </li>
        <li> Explore </li>
        <li> Completely hackable </li>
        <li> Fun </li>
      </ul>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-6">
      <h4>
        Newest
      </h4>
      <hr/>
      <%= render Script.order("updated_at DESC").limit(50) %>
    </div>

    <div class="col-md-6">
      <% if user_signed_in? %>
      <h4>
        Your Tracks
        <small style="font-size: 60%;"><%= link_to "New", new_script_path, class: "pull-right", style: 'position: inline-block; margin-top: 10px;' %></small>
      </h4>
      <hr/>
      <%= render current_user.scripts %>
      <hr/>
      <%= link_to "View All", scripts_path %>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Synthdrop" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

    <%= javascript_include_tag "application" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
    <% if user_signed_in? %>
      <script type="text/javascript" src="/profile/rc.js"></script>
    <% end %>
  </head>
  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container<%= "-fluid" if is_editor? %>">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if is_editor? %>
            <%= link_to scripts_path, class: "btn navbar-btn navbar-left navbar-back-btn" do %>
              <span class="glyphicon glyphicon-arrow-left"></span>
            <% end %>
          <% end %>
          <%= link_to root_url, class: "navbar-brand" do %>
            synthdrop <span class="current-file"><%= "/ #{content_for(:filename)}" if content_for?(:filename) %></span>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% unless is_editor? %>
            <ul class="nav navbar-nav">
              <li> <%= link_to "Tracks", scripts_path %> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li> <%= link_to "Settings", edit_profile_path %> </li>
                <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>
              <% else %>
                <li> <%= link_to "Sign in", new_user_session_path %> </li>
              <% end %>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li> <%= link_to "Play", '#', id: 'play-btn', data: { toggle: "tooltip", placement: "bottom", 'original-title': "cmd+enter" } %> </li>
              <li> <%= link_to "Stop", '#', id: 'stop-btn', data: { toggle: "tooltip", placement: "bottom", 'original-title': "cmd+." } %> </li>
              <li> <%= link_to "Save", '#', id: 'save-btn', data: { toggle: "tooltip", placement: "bottom", 'original-title': "cmd+s" } %> </li>
              <li> <%= link_to "Edit", edit_script_path(@script) %> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <div id='saving-notice' class='navbar-text'>
                <span class="label label-primary"> Saving ... </span>
              </div>
              <div id="slow-load-notice" class="navbar-text">
                <span class="label label-default"> Problem saving file. Retrying. </span>
              </div>
            </ul>
          <% end %>
        </div><!-- /.navbar-collapse -->

      </div>
    </nav>

    <div class="container<%= "-fluid" if is_editor? %>">
      <%= bootswatch_flash %>
      <%= yield(:content).presence || yield %>
    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/devise.html.erb
<% content_for :content do %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= yield %>
    </div>
  </div>
<% end %>

<%= render file: 'layouts/application' %>

app/views/scripts/_form.html.erb
<%= simple_form_for(@script, wrapper: :vertical_form) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, placeholder: "Title", required: false %>
    <%= f.input :description, placeholder: "Description" %>
    <%= f.input :language, label: "Language: ", required: false do %>
      <%= f.select :language, [ "CoffeeScript", "JavaScript" ], selected: @script.language_value %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
    <% unless @script.new_record? %>
      <%= link_to "Delete", script_path(@script), method: :delete, data: {confirm: "Are you sure?"}, class: 'text-danger', style: 'margin-left: 15px;' %>
    <% end %>
  </div>
<% end %>

app/views/scripts/_script.html.erb
<div class="row script-row">
  <div class="col-md-10">
    <h6>
      <% if current_user && script.user == current_user %>
        <%= link_to script.title, editor_script_path(script), style: "color: white;" %>
      <% else %>
        <%= link_to script.title, script_path(script), style: "color: white;" %>
      <% end %>
      <small><%= link_to "View", script_path(script), style: "display: inline-block; margin-left: 5px; margin-top: 11px;" %></small>
    </h6>
  </div>
  <div class="col-md-2 text-right">
    <% if user_signed_in? && current_user.id == script.user_id %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <p>
      <% if script.description.present? %>
      <%= script.description.strip %><%= '.' unless script.description.strip.ends_with?('.') %>
      <% end %>
      Updated <%= time_ago_in_words script.updated_at %> ago.
    </p>
  </div>
</div>

app/views/scripts/edit.html.erb
<% content_for :title, "Edit #{@script.title}" %>

<div class="row">
  <div class="col-md-6 col-md-push-3" style="padding-top: 30px;">
    <h3> Edit <%= @script.title %> </h3>
    <%= render 'form' %>
    <br />
    <p>
      <%= link_to "Back", scripts_path %>
    </p>
  </div>
</div>

app/views/scripts/editor.html.erb
<% content_for :title, "#{@script.title}#{@script.extension}" %>
<% content_for :filename, @script.title %>
<div class="row">
  <div class="col-md-12">
    <div id="editor" class="unloaded" data-authenticity-token="<%= form_authenticity_token %>" data-update-url="<%= script_path(@script, format: :json) %>" data-content-url="<%= script_content_url @script %>" data-language="<%= @script.language %>" data-keyboard="<%= current_user.keyboard %>"></div>
  </div>
</div>

<div id="editor-protip" class="text-center text-muted">
  Protip: open your browser's javascript console
</div>

app/views/scripts/index.html.erb
<% content_for :title, "Tracks" %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>
        Your Tracks <small>(<%= number_with_delimiter @script_count %>)</small>
        <div class="pull-right">
          <%= link_to "New", new_script_path, class: "btn btn-primary btn-sm" %>
        </div>
      </h3>
      <hr/>
      <%= render current_user.scripts %>
    </div>
  </div>
</div>

app/views/scripts/new.html.erb
<% content_for(:title, "New Track") %>
<div class="row">
  <div class="col-md-6 col-md-push-3" style="padding-top: 30px;">
    <h3> New Track </h3>
    <%= render 'form' %>
  </div>
</div>

app/views/scripts/show.html.erb
<% content_for(:title, @script.title) %>

<div class="row" style="">
  <div class="col-md-12">
    <h3>
      <%= @script.title %>
      <div class="pull-right">
        <% if @script.aws_id.present? %>
          <% if current_user && @script.user_id == current_user.id %>
            <%= link_to "Open Editor", editor_script_path(@script), class: "btn btn-default" %>
          <% end %>
          <%= link_to "Play", '#', id: "static-play-btn", class: "btn btn-primary", data: { url: @script.compiled_content_url } %>
          <%= link_to "Stop", '#', id: "stop-btn", class: "btn btn-primary" %>
        <% else %>
          <% if current_user && @script.user_id == current_user.id %>
            <%= link_to "Start Editing", editor_script_path(@script), class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </div>

      <span class="label label-info" style="font-size: 30%; position: relative; top: -5px; left: 10px;"><%= @script.language.titleize %></span>
    </h3>
  </div>
</div>

<% if (current_user && @script.user_id == current_user.id) || @script.description.present? %>
  <div class="row">
    <div class="col-md-12">
      <p class="well">
        <% if @script.description.present? %>
          <%= @script.description %>
          <% if current_user && @script.user_id == current_user.id %>
            - <%= link_to "Edit details", edit_script_path(@script) %>
          <% end %>
        <% else %>
          <% if current_user && @script.user_id == current_user.id %>
            <%= link_to "Add description", edit_script_path(@script) %>
          <% end %>
        <% end %>
      </p>
    </div>
  </div>
<% end %>

<% if @script.aws_id.present? %>
<div class="row">
  <div class="col-md-12">
    <div id="editor" class="unloaded demo" data-content-url="<%= script_content_url @script %>" data-language="<%= @script.language %>" data-read-only="true"></div>
  </div>
</div>
<% end %>

<div class="row" style="margin: 20px 0;">
  <div class="col-md-12">
    <p>
      <% if @script.aws_id.present? %>
      <div class="list-group">
        <div class="list-group-item">
          <h5 class="list-group-item-heading">Import This Code</h5>
          <p class="list-group-item-text">
            <samp style="font-size: 87%;">importScripts "<%= @script.compiled_content_url %>" # <%= @script.title %></samp>
          </p>
        </div>
      </div>
      <% end %>
    </p>
      Updated <%= time_ago_in_words @script.updated_at %> ago.
  </div>
</div>